const IRREGULAR_VERBS = [
  {
    v1: "bet",
    v1Hu: "fogad (pl. lóversenyen)",
    simplePast: "bet",
    simplePastExampleEn: "They bet on the biggest horse yesterday.",
    simplePastExampleHu: "A legnagyobb lóra fogadtak tegnap.",
    pastParticiple: "bet",
    pastParticipleExampleEn: "I have bet on the biggest horse.",
    pastParticipleExampleHu: "A legnagyobb lóra fogadtam.",
  },
  {
    v1: "bid",
    v1Hu: "licitál",
    simplePast: "bid",
    simplePastExampleEn: "We bid for a car yesterday.",
    simplePastExampleHu: "Tegnap egy autóra licitáltunk.",
    pastParticiple: "bid",
    pastParticipleExampleEn: "Susan has bid for an old chair.",
    pastParticipleExampleHu: " Susan egy régi székre licitált.",
  },
  {
    v1: "broadcast",
    v1Hu: "közvetít; sugároz;",
    simplePast: "broadcast",
    simplePastExampleEn: `We broadcast an interesting radio programme yesterday.`,
    simplePastExampleHu: "Tegnap egy érdekes rádióműsort sugároztunk.",
    pastParticiple: "broadcast",
    pastParticipleExampleEn: "Channel 4 has broadcast the news.",
    pastParticipleExampleHu: "A 4-es csatorna a híreket sugározta.",
  },

  {
    v1: "do",
    v1Hu: "csinál; végez; tesz",
    simplePast: "did",
    simplePastExampleEn: "They did a terrible job last week.",
    simplePastExampleHu: "Borzasztó munkát végeztek a múlt héten.",
    pastParticiple: "done",
    pastParticipleExampleEn: "She has done everything you asked.",
    pastParticipleExampleHu: "Megtett mindent, amit kértél.",
  },
  {
    v1: "fly",
    v1Hu: "repül",
    simplePast: "flew",
    simplePastExampleEn: "We flew from England to France last month.",
    simplePastExampleHu: "A múlt hónapban Angliából Franciaországba repültünk.",
    pastParticiple: "flown",
    pastParticipleExampleEn:
      "I have flown to many wonderful places since 2001.",
    pastParticipleExampleHu: "Nagy sok csodálatos helyre repültem 2001 óta.",
  },
  {
    v1: "go",
    v1Hu: "megy",
    simplePast: "went",
    simplePastExampleEn: "I went to the shop yesterday.",
    simplePastExampleHu: "Tegnap elmentem a boltba.",
    pastParticiple: "gone",
    pastParticipleExampleEn: "Sue has gone to the shop.",
    pastParticipleExampleHu: "Sue a boltba ment",
  },
  {
    v1: "begin",
    v1Hu: "kezdődik",
    simplePast: "began",
    simplePastExampleEn: "The match began an hour ago.",
    simplePastExampleHu: "A meccs egy órája kezdődött.",
    pastParticiple: "begun",
    pastParticipleExampleEn: "They have begun the attack.",
    pastParticipleExampleHu: "Elkezdték a támadást",
  },
  {
    v1: "drink",
    v1Hu: "iszik",
    simplePast: "drank",
    simplePastExampleEn: "The dog drank a lot of yesterday.",
    simplePastExampleHu: "A kutya nagyon sokat ivott tegnap.",
    pastParticiple: "drunk",
    pastParticipleExampleEn: "I have drunk eight coffees since yesterday",
    pastParticipleExampleHu: "8 kávét ittam tegnap óta.",
  },
  {
    v1: "ring",
    v1Hu: "cseng(et)",
    simplePast: "rang",
    simplePastExampleEn: "I rang the doorbell yesterday, but nobody came out.",
    simplePastExampleHu: "Tegnap csengettem, de senki se jött ki.",
    pastParticiple: "rang",
    pastParticipleExampleEn:
      "We have rung the doorbell at least 10 times since 1 o’clock.",
    pastParticipleExampleHu: "Legalább 10-szer csöngettünk 1 óra óta.",
  },
  {
    v1: "sing",
    v1Hu: "énekel",
    simplePast: "sang",
    simplePastExampleEn: "They sang a song last night.",
    simplePastExampleHu: "Tegnap este egy dalt énekeltek.",
    pastParticiple: "sung",
    pastParticipleExampleEn: "The parrot has sung three songs since I arrived.",
    pastParticipleExampleHu: "A papagáj három dalt énekelt, mióta megérkeztem.",
  },
  {
    v1: "swim",
    v1Hu: "úszik",
    simplePast: "swam",
    simplePastExampleEn: "They swam a lot yesterday.",
    simplePastExampleHu: "Sokat úsztak tegnap.",
    pastParticiple: "swum",
    pastParticipleExampleEn: "I have swum two kilometers since 8 o'clock.",
    pastParticipleExampleHu: "2 kilométert úsztam 8 óra óta.",
  },
  {
    v1: "sink",
    v1Hu: "elsüllyed",
    simplePast: "sank",
    simplePastExampleEn: "Our ship sank last year.",
    simplePastExampleHu: "Tavaly elsüllyedt a hajó.",
    pastParticiple: "sunk",
    pastParticipleExampleEn:
      "Five people have sunk since the accident happened.",
    pastParticipleExampleHu: "5 ember elsüllyedt, mióta megtörtént a baleset.",
  },
  {
    v1: "cut",
    v1Hu: "vág",
    simplePast: "cut",
    simplePastExampleEn: "I cut my finger yesterday.",
    simplePastExampleHu: "Megvágtam az ujjam tegnap.",
    pastParticiple: "cut",
    pastParticipleExampleEn: "They have cut the rope.",
    pastParticipleExampleHu: "Elvágták a kötelet.",
  },
  {
    v1: "hit",
    v1Hu: "üt",
    simplePast: "hit",
    simplePastExampleEn: "A car hit the cat.",
    simplePastExampleHu: "Elütötte egy autó a macskát.",
    pastParticiple: "hit",
    pastParticipleExampleEn: "Susan has hit the ball.",
    pastParticipleExampleHu: "Susan elütötte a labdát.",
  },
  {
    v1: "cost",
    v1Hu: "kerül",
    simplePast: "cost",
    simplePastExampleEn: "My car cost a lot of money.",
    simplePastExampleHu: "Az autóm sok pénzbe került.",
    pastParticiple: "cost",
    pastParticipleExampleEn: "The parrot has cost a lot of money.",
    pastParticipleExampleHu: "A papagáj sok pénzbe került.",
  },
  {
    v1: "hurt",
    v1Hu: "bánt; fáj",
    simplePast: "hurt",
    simplePastExampleEn: "I hurt Jack yesterday.",
    simplePastExampleHu: "Tegnap bántottam Jacket.",
    pastParticiple: "hurt",
    pastParticipleExampleEn: "They have hurt me.",
    pastParticipleExampleHu: "Bántottak engem.",
  },
  {
    v1: "let",
    v1Hu: "hagy;enged",
    simplePast: "let",
    simplePastExampleEn: "They let me go home yesterday.",
    simplePastExampleHu: "Tegnap hagytak hazemenni.",
    pastParticiple: "let",
    pastParticipleExampleEn: "They have let us go home.",
    pastParticipleExampleHu: "Hazaengedtek bennünket.",
  },
  {
    v1: "put",
    v1Hu: "tesz; rak",
    simplePast: "put",
    simplePastExampleEn: "They put milk in the fridge two days ago.",
    simplePastExampleHu: "Két napja tettek tejet a hűtőbe.",
    pastParticiple: "put",
    pastParticipleExampleEn: "I have put everything on the table.",
    pastParticipleExampleHu: "Mindent az asztalra tettem.",
  },
  {
    v1: "shut",
    v1Hu: "becsuk(ódik)",
    simplePast: "shut",
    simplePastExampleEn: "I shut the door five minutes ago.",
    simplePastExampleHu: "Öt perce csuktam be az ajtót.",
    pastParticiple: "shut",
    pastParticipleExampleEn: "They have shut the door.",
    pastParticipleExampleHu: "Becsukták az ajtót.",
  },
  {
    v1: "read",
    v1Hu: "olvas",
    simplePast: "read",
    simplePastExampleEn: "Marica read a book yesterday.",
    simplePastExampleHu: "Marica tegnap egy könyvet olvasott.",
    pastParticiple: "read",
    pastParticipleExampleEn: "They have read my diary.",
    pastParticipleExampleHu: "Elolvasták a naplómat.",
  },
  {
    v1: "become",
    v1Hu: "válik (valamivé)",
    simplePast: "became",
    simplePastExampleEn: "He became homeless a few years ago.",
    simplePastExampleHu: "Néhány éve vált hajléktalanná.",
    pastParticiple: "become",
    pastParticipleExampleEn: "I have become stronger since yesterday.",
    pastParticipleExampleHu: "Erősebb lettem tegnap óta.",
  },
  {
    v1: "come",
    v1Hu: "jön",
    simplePast: "came",
    simplePastExampleEn: "They came home yesterday.",
    simplePastExampleHu: "Tegnap hazajöttek.",
    pastParticiple: "come",
    pastParticipleExampleEn: "I have become to apologize.",
    pastParticipleExampleHu: "Azért jöttem, hogy bocsánatot kérjek.",
  },
  {
    v1: "run",
    v1Hu: "fut",
    simplePast: "ran",
    simplePastExampleEn: "Paul ran a hundred miles last year.",
    simplePastExampleHu: "Paul tavaly száz mérföldet futott.",
    pastParticiple: "run",
    pastParticipleExampleEn: "They have already run 10 kilometers.",
    pastParticipleExampleHu: "Már 10 kilométert futottak.",
  },
  {
    v1: "bend",
    v1Hu: "hajol, hajlít",
    simplePast: "bent",
    simplePastExampleEn: "My grandfather bent steel once.",
    simplePastExampleHu: "A nagyapám egyszer meghajlította az acélt.",
    pastParticiple: "bent",
    pastParticipleExampleEn: "I have bent my smartphone.",
    pastParticipleExampleHu: "Meghajlítottam az okostelefonomat.",
  },
  {
    v1: "bring",
    v1Hu: "hoz",
    simplePast: "brought",
    simplePastExampleEn: "They brought much food yesterday.",
    simplePastExampleHu: "Sok ételt hoztak tegnap.",
    pastParticiple: "brought",
    pastParticipleExampleEn: "I have brought a gift for you.",
    pastParticipleExampleHu: "Hoztam neked egy ajándékot.",
  },
  {
    v1: "build",
    v1Hu: "épít",
    simplePast: "built",
    simplePastExampleEn: "They built a new house last year.",
    simplePastExampleHu: "Tavaly építettek egy új házat.",
    pastParticiple: "built",
    pastParticipleExampleEn: "I have built a sandcastle.",
    pastParticipleExampleHu: "Építettem egy homokvárat.",
  },
  {
    v1: "buy",
    v1Hu: "vesz",
    simplePast: "bought",
    simplePastExampleEn: "We bought a car yesterday.",
    simplePastExampleHu: "Vettünk egy autót tegnap.",
    pastParticiple: "bought",
    pastParticipleExampleEn: "We have bought food.",
    pastParticipleExampleHu: "Vettünk ételt.",
  },
  {
    v1: "catch",
    v1Hu: "elkap; elér (pl. buszt)”",
    simplePast: "caught",
    simplePastExampleEn: "I caught the bus yesterday.",
    simplePastExampleHu: "Elértem a buszt tegnap.",
    pastParticiple: "caught",
    pastParticipleExampleEn: "They have caught the criminal.",
    pastParticipleExampleHu: "Elkapták a bűnözőt.",
  },
  {
    v1: "dig",
    v1Hu: "ás",
    simplePast: "dug",
    simplePastExampleEn: "Paul dug a huge hole yesterday.",
    simplePastExampleHu: "Paul tegnap egy óriási lyukat ásott.",
    pastParticiple: "dug",
    pastParticipleExampleEn: "I have dug two holes so far.",
    pastParticipleExampleHu: "Két lyukat ástam eddig.",
  },
  {
    v1: "feel",
    v1Hu: "érez; érzi magát",
    simplePast: "felt",
    simplePastExampleEn: "I felt something strange yesterday.",
    simplePastExampleHu: "Tegnap valami furcsát éreztem.",
    pastParticiple: "felt",
    pastParticipleExampleEn: "I have felt nothing.",
    pastParticipleExampleHu: "Nem éreztem semmit.",
  },
  {
    v1: "fight",
    v1Hu: "harcol",
    simplePast: "fought",
    simplePastExampleEn: "They fought a lot of battles last year.",
    simplePastExampleHu: "Sok csatát vívtak a múlt évben.",
    pastParticiple: "fought",
    pastParticipleExampleEn: "I have fought for my life.",
    pastParticipleExampleHu: "Az életemért harcoltam.",
  },
  {
    v1: "find",
    v1Hu: "(meg)talál",
    simplePast: "found",
    simplePastExampleEn: "They found the child last week.",
    simplePastExampleHu: "A múlt héten megtalálták a gyermeket.",
    pastParticiple: "found",
    pastParticipleExampleEn: "I have found something very valuable.",
    pastParticipleExampleHu: "Valami nagyon értékeset találtam.",
  },
  {
    v1: "get",
    v1Hu: "kap",
    simplePast: "got",
    simplePastExampleEn: "I got a book yesterday.",
    simplePastExampleHu: "Tegnap kaptam egy könyvet.",
    pastParticiple: "got",
    pastParticipleExampleEn: "They have got(ten) terrible news.",
    pastParticipleExampleHu: "Borzalmas híreket kaptak.",
  },
  {
    v1: "have",
    v1Hu: "van neki, birtokol",
    simplePast: "had",
    simplePastExampleEn: "I had three dogs when I was a child.",
    simplePastExampleHu: "Három kutyám volt, amikor gyerek voltam.",
    pastParticiple: "had",
    pastParticipleExampleEn: "I have had a terrible headache.",
    pastParticipleExampleHu: "Borzasztó fejfájásom volt.",
  },
  {
    v1: "hear",
    v1Hu: "hall",
    simplePast: "heard",
    simplePastExampleEn: "I heard you yesterday.",
    simplePastExampleHu: "Hallottalak tegnap.",
    pastParticiple: "heard",
    pastParticipleExampleEn: "Have you heard it?",
    pastParticipleExampleHu: "Hallottad?",
  },
  {
    v1: "hold",
    v1Hu: "tart; megfog",
    simplePast: "held",
    simplePastExampleEn: "I held a garden party yesterday.",
    simplePastExampleHu: "Tegnap egy kerti partit tartottam.",
    pastParticiple: "held",
    pastParticipleExampleEn: "I haven't held your baby since January.",
    pastParticipleExampleHu: "Január óta nem fogtam meg a babádat.",
  },
  {
    v1: "keep",
    v1Hu: "(meg)tart; (be)tart",
    simplePast: "kept",
    simplePastExampleEn: "I kept four chickens last year.",
    simplePastExampleHu: "Négy csirkét tartottam tavaly.",
    pastParticiple: "kept",
    pastParticipleExampleEn: "I haven't kept my promise.",
    pastParticipleExampleHu: "Nem tartottam be az ígéretemet.",
  },
  {
    v1: "lay",
    v1Hu: "(le)fektet",
    simplePast: "laid",
    simplePastExampleEn: "He laid the foundations of this organization.",
    simplePastExampleHu: "Ő fektette le ennek a szervezetnek az alapját.",
    pastParticiple: "laid",
    pastParticipleExampleEn: "I have laid my dog down on the table.",
    pastParticipleExampleHu: "Lefektettem a kutyámat az asztalra.",
  },
  {
    v1: "lead",
    v1Hu: "vezet",
    simplePast: "led",
    simplePastExampleEn: "My grandfather led many soldiers in the war.",
    simplePastExampleHu: "A nagyapám sok katonát vezetett a háborúban.",
    pastParticiple: "led",
    pastParticipleExampleEn: "The path has led us to a dead end.",
    pastParticipleExampleHu: "Az ösvény zsákutcába vezetett minket.",
  },
  {
    v1: "leave",
    v1Hu: "távozik, elmegy; ",
    simplePast: "left",
    simplePastExampleEn: "Paul and Sarah left an hour ago.",
    simplePastExampleHu: "Paul és Sarah egy órája elmentek.",
    pastParticiple: "left",
    pastParticipleExampleEn: "You have left your coat on the chair.",
    pastParticipleExampleHu: "A széken hagytad a kabátodat.",
  },
  {
    v1: "lend",
    v1Hu: "kölcsönad",
    simplePast: "lent",
    simplePastExampleEn: "She lent me much money yesterday.",
    simplePastExampleHu: "Tegnap sok pénzt adott nekem kölcsön.",
    pastParticiple: "lent",
    pastParticipleExampleEn: "They haven't lent me any money.",
    pastParticipleExampleHu: "Nem adtak kölcsön semennyi pénzt.",
  },
  {
    v1: "lose",
    v1Hu: "(el)veszít",
    simplePast: "lost",
    simplePastExampleEn: "They lost the match yesterday.",
    simplePastExampleHu: "Tegnap elvesztették a mérkőzést.",
    pastParticiple: "lost",
    pastParticipleExampleEn: "I have lost my keys.",
    pastParticipleExampleHu: "Elvesztettem a kulcsomat.",
  },
  {
    v1: "make",
    v1Hu: "csinál",
    simplePast: "made",
    simplePastExampleEn: "They made a lot of money last year.",
    simplePastExampleHu: "Sok pénzt csináltak a múlt évben.",
    pastParticiple: "made",
    pastParticipleExampleEn: "I have made a serious mistake.",
    pastParticipleExampleHu: "Komoly hibát vétettem [csináltam].",
  },
  {
    v1: "mean",
    v1Hu: "jelent, gondol",
    simplePast: "meant",
    simplePastExampleEn: "We meant nothing wrong last night.",
    simplePastExampleHu: "Semmi rosszra nem gondoltunk tegnap este.",
    pastParticiple: "meant",
    pastParticipleExampleEn: "It hasn't meant anything important for me.",
    pastParticipleExampleHu: "Semmi fontosat nem jelentett számomra.",
  },
  {
    v1: "meet",
    v1Hu: "találkozik",
    simplePast: "met",
    simplePastExampleEn: "They met at the café yesterday.",
    simplePastExampleHu: "Tegnap találkoztak a kávézóban.",
    pastParticiple: "met",
    pastParticipleExampleEn: "I have already met your sister.",
    pastParticipleExampleHu: "Már találkoztam a nővéreddel.",
  },
  {
    v1: "pay",
    v1Hu: "fizet",
    simplePast: "paid",
    simplePastExampleEn: "She paid the bill at the restaurant.",
    simplePastExampleHu: "Kifizette a számlát a vendéglőben.",
    pastParticiple: "paid",
    pastParticipleExampleEn: "I have already paid for the tickets.",
    pastParticipleExampleHu: "Már kifizettem a jegyeket.",
  },
  {
    v1: "say",
    v1Hu: "mond",
    simplePast: "said",
    simplePastExampleEn: "He said he would be here on time.",
    simplePastExampleHu: "Mondta, hogy időben itt lesz.",
    pastParticiple: "said",
    pastParticipleExampleEn: "They have said enough about the topic.",
    pastParticipleExampleHu: "Elég sokat mondtak a témáról.",
  },
  {
    v1: "sell",
    v1Hu: "elad",
    simplePast: "sold",
    simplePastExampleEn: "They sold their old car last week.",
    simplePastExampleHu: "Eladták régi autójukat múlt héten.",
    pastParticiple: "sold",
    pastParticipleExampleEn: "I have sold all my belongings.",
    pastParticipleExampleHu: "Eladtam az összes holmimat.",
  },
  {
    v1: "send",
    v1Hu: "küld",
    simplePast: "sent",
    simplePastExampleEn: "She sent an email to her friend yesterday.",
    simplePastExampleHu: "Tegnap elküldött egy emailt a barátjának.",
    pastParticiple: "sent",
    pastParticipleExampleEn: "I have already sent the package.",
    pastParticipleExampleHu: "Már elküldtem a csomagot.",
  },
  {
    v1: "sit",
    v1Hu: "ül",
    simplePast: "sat",
    simplePastExampleEn: "He sat on the chair and waited.",
    simplePastExampleHu: "Leült a székre és várt.",
    pastParticiple: "sat",
    pastParticipleExampleEn: "I have already sat at this table before.",
    pastParticipleExampleHu: "Már leültem erre az asztalra.",
  },
  {
    v1: "sleep",
    v1Hu: "alszik",
    simplePast: "slept",
    simplePastExampleEn: "I slept for eight hours last night.",
    simplePastExampleHu: "Tegnap éjjel nyolc órát aludtam.",
    pastParticiple: "slept",
    pastParticipleExampleEn: "She has slept well and feels refreshed.",
    pastParticipleExampleHu: "Jól aludt és frissnek érzi magát.",
  },
  {
    v1: "spend",
    v1Hu: "tölt, költ",
    simplePast: "spent",
    simplePastExampleEn: "They spent the whole day at the beach.",
    simplePastExampleHu: "Az egész napot a strandon töltötték.",
    pastParticiple: "spent",
    pastParticipleExampleEn: "I have already spent all my money.",
    pastParticipleExampleHu: "Már elköltöttem az összes pénzem.",
  },
  {
    v1: "stand",
    v1Hu: "áll",
    simplePast: "stood",
    simplePastExampleEn: "We stood in line for hours.",
    simplePastExampleHu: "Órákon át álltunk sorban.",
    pastParticiple: "stood",
    pastParticipleExampleEn: "He has stood on that stage many times.",
    pastParticipleExampleHu: "Sokszor állt már arra a színpadra.",
  },
  {
    v1: "teach",
    v1Hu: "tanít",
    simplePast: "taught",
    simplePastExampleEn: "She taught English at the university.",
    simplePastExampleHu: "Angolt tanított az egyetemen.",
    pastParticiple: "taught",
    pastParticipleExampleEn: "Your master has taught you well.",
    pastParticipleExampleHu: "A mestered jól tanított.",
  },
  {
    v1: "tell",
    v1Hu: "mond, mesél",
    simplePast: "told",
    simplePastExampleEn: "He told me an interesting story.",
    simplePastExampleHu: "Mesélt nekem egy érdekes történetet.",
    pastParticiple: "told",
    pastParticipleExampleEn: "She has told me about her plans for the weekend.",
    pastParticipleExampleHu: "Mesélt nekem a hétvégi terveiről.",
  },
  {
    v1: "think",
    v1Hu: "gondol",
    simplePast: "thought",
    simplePastExampleEn: "I thought about your suggestion.",
    simplePastExampleHu: "Gondolkodtam a javaslatodon.",
    pastParticiple: "thought",
    pastParticipleExampleEn: "He has always thought highly of you.",
    pastParticipleExampleHu: "Mindig nagyra tartott téged.",
  },
  {
    v1: "understand",
    v1Hu: "megért",
    simplePast: "understood",
    simplePastExampleEn: "We understood the instructions clearly.",
    simplePastExampleHu: "Egyértelműen megértettük az utasításokat.",
    pastParticiple: "understood",
    pastParticipleExampleEn: "She has understood the concept completely.",
    pastParticipleExampleHu: "Teljesen megértette a koncepciót.",
  },
  {
    v1: "win",
    v1Hu: "nyer",
    simplePast: "won",
    simplePastExampleEn: "They won the game last night.",
    simplePastExampleHu: "Tegnap este megnyerték a játékot.",
    pastParticiple: "won",
    pastParticipleExampleEn: "He has won many awards in his career.",
    pastParticipleExampleHu: "Sok díjat nyert karrierje során.",
  },
  {
    v1: "beat",
    v1Hu: "ver",
    simplePast: "beat",
    simplePastExampleEn: "He beat his opponent in the boxing match.",
    simplePastExampleHu: "Legyőzte ellenfelét a bokszmeccsen.",
    pastParticiple: "beaten",
    pastParticipleExampleEn: "They have beaten their previous record.",
    pastParticipleExampleHu: "Megdöntötték az előző rekordjukat.",
  },
  {
    v1: "bite",
    v1Hu: "harap",
    simplePast: "bit",
    simplePastExampleEn: "A dog bit me yesterday.",
    simplePastExampleHu: "Egy kutya megharapott engem tegnap.",
    pastParticiple: "bitten",
    pastParticipleExampleEn: "The dog has bitten you..",
    pastParticipleExampleHu: "Megharaptak a A kutya megharapott téged.",
  },
  {
    v1: "blow",
    v1Hu: "fúj",
    simplePast: "blew",
    simplePastExampleEn: "The wind blew the leaves off the tree.",
    simplePastExampleHu: "A szél lefújta a leveleket a fáról.",
    pastParticiple: "blown",
    pastParticipleExampleEn: "The wind has blown.",
    pastParticipleExampleHu: "Fújt a szél.",
  },
  {
    v1: "draw",
    v1Hu: "rajzol",
    simplePast: "drew",
    simplePastExampleEn: "She drew a beautiful picture of a sunset.",
    simplePastExampleHu: "Rajzolt egy gyönyörű képet egy naplementéről.",
    pastParticiple: "drawn",
    pastParticipleExampleEn: "I have drawn many portraits in my art class.",
    pastParticipleExampleHu: "Sok portrét rajzoltam a művészeti órán.",
  },
  {
    v1: "drive",
    v1Hu: "vezet",
    simplePast: "drove",
    simplePastExampleEn: "I drove a hundred miles yesterday.",
    simplePastExampleHu: "Száz mérföldet vezettem tegnap.",
    pastParticiple: "driven",
    pastParticipleExampleEn:
      "She has driven long distances without getting tired.",
    pastParticipleExampleHu: "Hosszú távokat vezetett fáradás nélkül.",
  },
  {
    v1: "eat",
    v1Hu: "eszik",
    simplePast: "ate",
    simplePastExampleEn: "We ate dinner at a fancy restaurant last night.",
    simplePastExampleHu: "Tegnap este vacsoráztunk egy elegáns étteremben.",
    pastParticiple: "eaten",
    pastParticipleExampleEn: "I have eaten all the cake.",
    pastParticipleExampleHu: "Megtudtam enni az összes tortát.",
  },
  {
    v1: "fall",
    v1Hu: "esik",
    simplePast: "fell",
    simplePastExampleEn: "The glass fell from my hand yesterday.",
    simplePastExampleHu: "Tegnap kiesett a pohár a kezemből.",
    pastParticiple: "fallen",
    pastParticipleExampleEn: "They have fallen down.",
    pastParticipleExampleHu: "Leestek.",
  },
  {
    v1: "forgive",
    v1Hu: "megbocsát",
    simplePast: "forgave",
    simplePastExampleEn: "She forgave him for his mistake.",
    simplePastExampleHu: "Megbocsátott neki a hibájáért.",
    pastParticiple: "forgiven",
    pastParticipleExampleEn: "I have forgiven you.",
    pastParticipleExampleHu: "Megbocsájtottam neked.",
  },
  {
    v1: "give",
    v1Hu: "ad",
    simplePast: "gave",
    simplePastExampleEn: "They gave me a present for my birthday.",
    simplePastExampleHu: "Ajándékot adtak nekem a születésnapomra.",
    pastParticiple: "given",
    pastParticipleExampleEn: "She has given me some valuable advice.",
    pastParticipleExampleHu: "Adott nekem néhány értékes tanácsot.",
  },
  {
    v1: "hide",
    v1Hu: "elrejt",
    simplePast: "hid",
    simplePastExampleEn: "He hid the key under the mat.",
    simplePastExampleHu: "Elrejtette a kulcsot a lábtörlő alá.",
    pastParticiple: "hidden",
    pastParticipleExampleEn: "I have hidden everything.",
    pastParticipleExampleHu: "Mindent elrejtettem.",
  },
  {
    v1: "know",
    v1Hu: "tud, ismer",
    simplePast: "knew",
    simplePastExampleEn: "She knew the answer to the question.",
    simplePastExampleHu: "Tudta a választ a kérdésre.",
    pastParticiple: "known",
    pastParticipleExampleEn: "He has known her for many years.",
    pastParticipleExampleHu: "Régóta ismeri őt.",
  },
  {
    v1: "ride",
    v1Hu: "lovagol, utazik",
    simplePast: "rode",
    simplePastExampleEn: "They rode their bikes in the park.",
    simplePastExampleHu: "Bringával mentek a parkban.",
    pastParticiple: "ridden",
    pastParticipleExampleEn: "I have ridden a horse before.",
    pastParticipleExampleHu: "Már lovagoltam lovon.",
  },
  {
    v1: "rise",
    v1Hu: "emelkedik, felkel",
    simplePast: "rose",
    simplePastExampleEn: "The sun rose early this morning.",
    simplePastExampleHu: "A nap korán felkelt ma reggel.",
    pastParticiple: "risen",
    pastParticipleExampleEn: "The tide has risen significantly.",
    pastParticipleExampleHu: "A dagály jelentősen emelkedett.",
  },
  {
    v1: "see",
    v1Hu: "lát",
    simplePast: "saw",
    simplePastExampleEn: "I saw a beautiful sunset yesterday.",
    simplePastExampleHu: "Láttam egy gyönyörű naplementét tegnap.",
    pastParticiple: "seen",
    pastParticipleExampleEn: "She has seen that movie multiple times.",
    pastParticipleExampleHu: "Már többször látta azt a filmet.",
  },
  {
    v1: "show",
    v1Hu: "megmutat",
    simplePast: "showed",
    simplePastExampleEn: "He showed me how to solve the math problem.",
    simplePastExampleHu:
      "Megmutatta nekem, hogyan oldjam meg a matek feladatot.",
    pastParticiple: "shown",
    pastParticipleExampleEn: "He has shown me his scar.",
    pastParticipleExampleHu: "Megmutatta a sebhelyét.",
  },
  {
    v1: "take",
    v1Hu: "visz, vesz",
    simplePast: "took",
    simplePastExampleEn: "He took a shower in the morning.",
    simplePastExampleHu: "Reggel vett egy zuhanyt.",
    pastParticiple: "taken",
    pastParticipleExampleEn: "I have taken her dog back.",
    pastParticipleExampleHu: "Visszavittem a kutyáját.",
  },
  {
    v1: "throw",
    v1Hu: "dob",
    simplePast: "threw",
    simplePastExampleEn: "The protesters threw bricks at the police yesterday.",
    simplePastExampleHu: "Tegnap a tüntetők téglákkal dobálták a rendőröket.",
    pastParticiple: "thrown",
    pastParticipleExampleEn: "I've thrown the ball to Paul.",
    pastParticipleExampleHu: "Paulnak dobtam a labdát..",
  },
  {
    v1: "write",
    v1Hu: "ír",
    simplePast: "wrote",
    simplePastExampleEn:
      "She wrote a beautiful poem for her friend's birthday.",
    simplePastExampleHu: "Írt egy gyönyörű verset a barátja születésnapjára.",
    pastParticiple: "written",
    pastParticipleExampleEn: "I have written a letter to my grandparents.",
    pastParticipleExampleHu: "Írtam egy levelet a nagyszüleimnek.",
  },
  {
    v1: "awake",
    v1Hu: "felébred",
    simplePast: "awoke",
    simplePastExampleEn: "She awoke early in the morning.",
    simplePastExampleHu: "Korán felébredt reggel.",
    pastParticiple: "awoken",
    pastParticipleExampleEn: "I have awoken from a deep sleep.",
    pastParticipleExampleHu: "Felébredtem egy mély álomból.",
  },
  {
    v1: "break",
    v1Hu: "eltör",
    simplePast: "broke",
    simplePastExampleEn: "My leg broke last week..",
    simplePastExampleHu: "A múlt héten eltört a lábam.",
    pastParticiple: "broken",
    pastParticipleExampleEn: "The cat has broken the vase.",
    pastParticipleExampleHu: "A macska eltörte a vázát.",
  },
  {
    v1: "choose",
    v1Hu: "választ",
    simplePast: "chose",
    simplePastExampleEn: "She chose the blue dress for the party.",
    simplePastExampleHu: "Kiválasztotta a kék ruhát a bulira.",
    pastParticiple: "chosen",
    pastParticipleExampleEn: "I have chosen my career path.",
    pastParticipleExampleHu: "Kiválasztottam a karrierutamat.",
  },
  {
    v1: "forget",
    v1Hu: "elfelejt",
    simplePast: "forgot",
    simplePastExampleEn: "He forgot his keys at home.",
    simplePastExampleHu: "Otthon felejtette a kulcsait.",
    pastParticiple: "forgotten",
    pastParticipleExampleEn:
      "I have forgotten the password to my email account.",
    pastParticipleExampleHu: "Elfelejtettem az e-mail fiókom jelszavát.",
  },
  {
    v1: "freeze",
    v1Hu: "megfagy",
    simplePast: "froze",
    simplePastExampleEn: "The water froze in the cold weather.",
    simplePastExampleHu: "A víz megfagyott a hideg időben.",
    pastParticiple: "frozen",
    pastParticipleExampleEn: "I have frozen the meat.",
    pastParticipleExampleHu: "Lefagyasztottam a húst.",
  },
  {
    v1: "grow",
    v1Hu: "nő, növekszik",
    simplePast: "grew",
    simplePastExampleEn: "The tree grew tall and strong.",
    simplePastExampleHu: "A fa magasra és erőssé nőtt.",
    pastParticiple: "grown",
    pastParticipleExampleEn: "I haven't grown at all since 2010.",
    pastParticipleExampleHu: "Egyáltalán nem nőttem 2010 óta.",
  },
  {
    v1: "speak",
    v1Hu: "beszél",
    simplePast: "spoke",
    simplePastExampleEn: "They spoke about bad things yesterday.",
    simplePastExampleHu: "Tegnap rossz dolgokról beszélgettek.",
    pastParticiple: "spoken",
    pastParticipleExampleEn: "She has spoken to the manager about the issue.",
    pastParticipleExampleHu: "Beszélt a vezetővel az ügyről.",
  },
  {
    v1: "tear",
    v1Hu: "szakít, tép",
    simplePast: "tore",
    simplePastExampleEn: "He tore the paper into small pieces.",
    simplePastExampleHu: "Kicsi darabokra szakította a papírt.",
    pastParticiple: "torn",
    pastParticipleExampleEn: "The flag was torn by the strong wind.",
    pastParticipleExampleHu: "A zászlót szétrázta a erős szél.",
  },
  {
    v1: "wake",
    v1Hu: "felébred",
    simplePast: "woke",
    simplePastExampleEn: "She woke up early this morning.",
    simplePastExampleHu: "Korán felébredt ma reggel.",
    pastParticiple: "woken",
    pastParticipleExampleEn: "I have woken up feeling refreshed.",
    pastParticipleExampleHu: "Felébredtem, frissen éreztem magam.",
  },
  {
    v1: "wear",
    v1Hu: "visel",
    simplePast: "wore",
    simplePastExampleEn: "He wore a black suit to the wedding.",
    simplePastExampleHu: "Fekete öltönyt viselt az esküvőn.",
    pastParticiple: "worn",
    pastParticipleExampleEn: "They have worn blue shirts.",
    pastParticipleExampleHu: "Kék inget hordtak.",
  },
];

export default IRREGULAR_VERBS;
